services:
  - type: web
    name: prizm-salon
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install && npm run build
    startCommand: npm run prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: GATEWAY_PORT
        value: 3001
